#!/usr/bin/env python3
"""
Generate Windows vc17 project files for the PCL static library.

Upstream PCL gitignores PCL.* under windows/, so fresh clones do not include
PCL.vcxproj. This script recreates them from src/pcl/*.cpp so CI can build.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path


PROJECT_GUID = "{EE596EFC-8DD0-41D2-A391-B28B5D3CDB99}"
FILTER_GUID = "{257d8c66-9dc8-4c9a-929d-f2722c781304}"


def find_cpp_sources(pcl_src: Path) -> list[str]:
    sources = sorted(p.name for p in pcl_src.glob("*.cpp"))
    if not sources:
        raise SystemExit(f"No .cpp sources found in {pcl_src}")
    return sources


def generate_vcxproj(sources: list[str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    compile_items = "\n".join(
        f'    <ClCompile Include="..\\..\\{name}"/>' for name in sources
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!--
######################################################################
# Generated by VeraLuxPixInsight generate_pcl_vcxproj.py
# Mirrors PixInsight Makefile Generator output for PCL StaticLibrary
######################################################################
# Generated on .... {now}
# Project id ...... PCL
# Project type .... StaticLibrary
# Platform ........ Windows/vc17
######################################################################
-->
<Project DefaultTargets="Build" ToolsVersion="17.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>{PROJECT_GUID}</ProjectGuid>
    <RootNamespace>PixInsight</RootNamespace>
    <Keyword>Win32Proj</Keyword>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>StaticLibrary</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <PlatformToolset>v143</PlatformToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>StaticLibrary</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet>
    <PlatformToolset>v143</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="PropertySheets">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <_ProjectFileVersion>10.0.40219.1</_ProjectFileVersion>
    <OutDir Condition="'$(Configuration)|$(Platform)'=='Release|x64'">$(PCLLIBDIR64)\\</OutDir>
    <IntDir Condition="'$(Configuration)|$(Platform)'=='Release|x64'">$(Platform)\\$(Configuration)\\</IntDir>
    <OutDir Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">$(PCLLIBDIR64)\\</OutDir>
    <IntDir Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">$(Platform)\\$(Configuration)\\</IntDir>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='Release|x64'">PCL-pxi</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">PCL-pxi</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Midl>
      <TargetEnvironment>X64</TargetEnvironment>
    </Midl>
    <ClCompile>
      <Optimization>MaxSpeed</Optimization>
      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <OmitFramePointers>true</OmitFramePointers>
      <WholeProgramOptimization>false</WholeProgramOptimization>
      <AdditionalIncludeDirectories>$(PCLINCDIR);$(PCLSRCDIR)\\3rdparty;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>WIN32;WIN64;_WINDOWS;UNICODE;__PCL_WINDOWS;__PCL_NO_WIN32_MINIMUM_VERSIONS;__PCL_AVX2;__PCL_FMA;_NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <StringPooling>true</StringPooling>
      <ExceptionHandling>Async</ExceptionHandling>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <BufferSecurityCheck>false</BufferSecurityCheck>
      <FunctionLevelLinking>false</FunctionLevelLinking>
      <FloatingPointModel>Fast</FloatingPointModel>
      <PrecompiledHeader></PrecompiledHeader>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat></DebugInformationFormat>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <RuntimeTypeInfo>true</RuntimeTypeInfo>
      <EnableEnhancedInstructionSet>AdvancedVectorExtensions2</EnableEnhancedInstructionSet>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <AdditionalOptions>/Zc:__cplusplus /permissive- %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Lib>
      <OutputFile>$(PCLLIBDIR64)\\PCL-pxi.lib</OutputFile>
    </Lib>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Midl>
      <TargetEnvironment>X64</TargetEnvironment>
    </Midl>
    <ClCompile>
      <Optimization>Disabled</Optimization>
      <AdditionalIncludeDirectories>$(PCLINCDIR);$(PCLSRCDIR)\\3rdparty;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>WIN32;WIN64;_WINDOWS;UNICODE;__PCL_WINDOWS;__PCL_NO_WIN32_MINIMUM_VERSIONS;__PCL_AVX2;__PCL_FMA;_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ExceptionHandling>Async</ExceptionHandling>
      <MinimalRebuild>true</MinimalRebuild>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <PrecompiledHeader></PrecompiledHeader>
      <WarningLevel>Level3</WarningLevel>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <RuntimeTypeInfo>true</RuntimeTypeInfo>
      <EnableEnhancedInstructionSet>AdvancedVectorExtensions2</EnableEnhancedInstructionSet>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <AdditionalOptions>/Zc:__cplusplus /permissive- %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Lib>
      <OutputFile>$(PCLLIBDIR64)\\PCL-pxi.lib</OutputFile>
    </Lib>
  </ItemDefinitionGroup>
  <ItemGroup>
{compile_items}
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets"/>
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>
"""


def generate_filters(sources: list[str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    compile_items = "\n".join(
        f'    <ClCompile Include="..\\..\\{name}">\n'
        f"        <Filter>Source Files</Filter>\n"
        f"    </ClCompile>"
        for name in sources
    )
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!--
######################################################################
# Generated by VeraLuxPixInsight generate_pcl_vcxproj.py
######################################################################
# Generated on .... {now}
# Project id ...... PCL
# Project type .... StaticLibrary
# Platform ........ Windows/vc17
######################################################################
-->
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Filter Include="Source Files">
      <UniqueIdentifier>{FILTER_GUID}</UniqueIdentifier>
    </Filter>
  </ItemGroup>
  <ItemGroup>
{compile_items}
  </ItemGroup>
</Project>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate PCL Windows vc17 project files")
    parser.add_argument(
        "--pcl-path",
        required=True,
        help="Path to the PCL repository root",
    )
    args = parser.parse_args()

    pcl_root = Path(args.pcl_path).resolve()
    pcl_src = pcl_root / "src" / "pcl"
    out_dir = pcl_src / "windows" / "vc17"

    if not pcl_src.is_dir():
        raise SystemExit(f"PCL source directory not found: {pcl_src}")

    sources = find_cpp_sources(pcl_src)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "x64" / "Release").mkdir(parents=True, exist_ok=True)
    (out_dir / "x64" / "Debug").mkdir(parents=True, exist_ok=True)

    vcxproj_path = out_dir / "PCL.vcxproj"
    filters_path = out_dir / "PCL.vcxproj.filters"
    vcxproj_path.write_text(generate_vcxproj(sources), encoding="utf-8")
    filters_path.write_text(generate_filters(sources), encoding="utf-8")

    print(f"Generated {vcxproj_path} ({len(sources)} sources)")
    print(f"Generated {filters_path}")


if __name__ == "__main__":
    main()
